---

root: true

extends:
  - airbnb


parser: "@babel/eslint-parser"

parserOptions:
  ecmaVersion: latest

env:
  browser: true
  node: true
  jest: true

settings:
  import/resolver:
    - node
    - webpack

rules:
  import/extensions: 0
  import/prefer-default-export: 0
  react/prop-types: 0
  no-console: 0
  import/no-unresolved: 0
